# Configuration file for statichost.eu
[site]
title = "Ljudtranskribering & Sammanfattning"
description = "En webbapp för att transkribera och sammanfatta ljud- eller videofiler på svenska."

[headers]
# Required for SharedArrayBuffer (needed by transformers.js)
"/*" = { "Cross-Origin-Embedder-Policy" = "require-corp", "Cross-Origin-Opener-Policy" = "same-origin" }

# Correct MIME types
"/js/*.js" = { "Content-Type" = "application/javascript" }
"/css/*.css" = { "Content-Type" = "text/css" }
